apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-fluentd-s3-config
  namespace: kube-system
data:
  S3_LOGS_BUCKET_NAME: tulipdata-agent-logs
  S3_LOGS_BUCKET_PREFIX: agents/logs/
  S3_LOGS_BUCKET_REGION: us-east-1
